site_name: "Asked.io:"
site_twitter: "@asked_io"
site_url: https://asked.io
site_slogan: A day-to-day log of the questions we've asked &amp; the answers we've found.
mailchimp_url: //gamecp.us9.list-manage.com/subscribe/post?u=c51506a011e686ef30cdf42cb&amp;id=90c78ff308
post_per_page: 8
language: en